"""Phase 7 Variance Engine

Revision ID: 679a48309843
Revises: c8bd7347d08a
Create Date: 2026-09-28 00:35:51.310551
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '679a48309843'
down_revision: Union[str, None] = 'c8bd7347d08a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('variances',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('activity_id', sa.UUID(), nullable=True),
    sa.Column('variance_type', sa.Enum('SCHEDULE', 'QUANTITY', 'SEQUENCE', name='variancetype'), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='severitylevel'), server_default='INFO', nullable=False),
    sa.Column('planned_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('planned_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delta_days', sa.Float(), nullable=True),
    sa.Column('planned_quantity', sa.Float(), nullable=True),
    sa.Column('actual_quantity', sa.Float(), nullable=True),
    sa.Column('quantity_delta', sa.Float(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_id'], ['execution_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_variances_event_id'), 'variances', ['event_id'], unique=False)
    op.create_index(op.f('ix_variances_project_id'), 'variances', ['project_id'], unique=False)
    op.create_index(op.f('ix_variances_variance_type'), 'variances', ['variance_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_variances_variance_type'), table_name='variances')
    op.drop_index(op.f('ix_variances_project_id'), table_name='variances')
    op.drop_index(op.f('ix_variances_event_id'), table_name='variances')
    op.drop_table('variances')
    # ### end Alembic commands ###
