"""Phase 2 Schedules

Revision ID: beccca627293
Revises: 001_foundation
Create Date: 2026-09-28 00:02:34.528952
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'beccca627293'
down_revision: Union[str, None] = '001_foundation'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedules',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedules_project_id'), 'schedules', ['project_id'], unique=False)
    op.create_table('schedule_versions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('schedule_id', sa.UUID(), nullable=False),
    sa.Column('version_num', sa.Integer(), nullable=False),
    sa.Column('source_file_name', sa.String(length=255), nullable=True),
    sa.Column('imported_by_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'ARCHIVED', name='schedulestatus'), server_default='DRAFT', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['imported_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schedule_id', 'version_num', name='uq_schedule_version')
    )
    op.create_index(op.f('ix_schedule_versions_schedule_id'), 'schedule_versions', ['schedule_id'], unique=False)
    op.create_table('activities',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('schedule_version_id', sa.UUID(), nullable=False),
    sa.Column('activity_code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('wbs_level', sa.String(length=50), nullable=True),
    sa.Column('discipline', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('planned_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('planned_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['activities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schedule_version_id'], ['schedule_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schedule_version_id', 'activity_code', name='uq_version_activity_code')
    )
    op.create_index(op.f('ix_activities_activity_code'), 'activities', ['activity_code'], unique=False)
    op.create_index(op.f('ix_activities_schedule_version_id'), 'activities', ['schedule_version_id'], unique=False)
    op.create_table('activity_dependencies',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('predecessor_id', sa.UUID(), nullable=False),
    sa.Column('successor_id', sa.UUID(), nullable=False),
    sa.Column('dependency_type', sa.Enum('FS', 'SS', 'FF', 'SF', name='dependencytype'), server_default='FS', nullable=False),
    sa.Column('lag', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['predecessor_id'], ['activities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['successor_id'], ['activities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('predecessor_id', 'successor_id', name='uq_activity_dependency')
    )
    op.create_index(op.f('ix_activity_dependencies_predecessor_id'), 'activity_dependencies', ['predecessor_id'], unique=False)
    op.create_index(op.f('ix_activity_dependencies_successor_id'), 'activity_dependencies', ['successor_id'], unique=False)
    op.drop_constraint('projects_code_key', 'projects', type_='unique')
    op.drop_index('ix_projects_code', table_name='projects')
    op.create_index(op.f('ix_projects_code'), 'projects', ['code'], unique=True)
    op.drop_constraint('roles_name_key', 'roles', type_='unique')
    op.drop_index('ix_roles_name', table_name='roles')
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_unique_constraint('users_email_key', 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.create_index('ix_roles_name', 'roles', ['name'], unique=False)
    op.create_unique_constraint('roles_name_key', 'roles', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_projects_code'), table_name='projects')
    op.create_index('ix_projects_code', 'projects', ['code'], unique=False)
    op.create_unique_constraint('projects_code_key', 'projects', ['code'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_activity_dependencies_successor_id'), table_name='activity_dependencies')
    op.drop_index(op.f('ix_activity_dependencies_predecessor_id'), table_name='activity_dependencies')
    op.drop_table('activity_dependencies')
    op.drop_index(op.f('ix_activities_schedule_version_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_activity_code'), table_name='activities')
    op.drop_table('activities')
    op.drop_index(op.f('ix_schedule_versions_schedule_id'), table_name='schedule_versions')
    op.drop_table('schedule_versions')
    op.drop_index(op.f('ix_schedules_project_id'), table_name='schedules')
    op.drop_table('schedules')
    # ### end Alembic commands ###
