"""Phase 3 Execution Events

Revision ID: c8bd7347d08a
Revises: beccca627293
Create Date: 2026-09-28 00:13:39.616161
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8bd7347d08a'
down_revision: Union[str, None] = 'beccca627293'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by_id', sa.UUID(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_project_id'), 'evidence', ['project_id'], unique=False)
    op.create_table('execution_events',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('reported_by_id', sa.UUID(), nullable=True),
    sa.Column('source_type', sa.Enum('TEXT', 'AUDIO', 'IMAGE', 'PDF', 'EXCEL', name='sourcetype'), server_default='TEXT', nullable=False),
    sa.Column('raw_input', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING_PROCESSING', 'EXTRACTED', 'MATCHED', 'REVIEW_REQUIRED', 'APPROVED', 'REJECTED', 'FAILED', name='eventstatus'), server_default='PENDING_PROCESSING', nullable=False),
    sa.Column('extracted_data', sa.JSON(), nullable=True),
    sa.Column('normalized_text', sa.Text(), nullable=True),
    sa.Column('matched_activity_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['matched_activity_id'], ['activities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reported_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_events_project_id'), 'execution_events', ['project_id'], unique=False)
    op.create_index(op.f('ix_execution_events_status'), 'execution_events', ['status'], unique=False)
    op.create_table('event_evidence',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('evidence_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['execution_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', 'evidence_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_evidence')
    op.drop_index(op.f('ix_execution_events_status'), table_name='execution_events')
    op.drop_index(op.f('ix_execution_events_project_id'), table_name='execution_events')
    op.drop_table('execution_events')
    op.drop_index(op.f('ix_evidence_project_id'), table_name='evidence')
    op.drop_table('evidence')
    # ### end Alembic commands ###
